services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: parranda_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: parranda_events
      POSTGRES_USER: parranda_user
      POSTGRES_PASSWORD: parranda_pass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parranda_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parranda_user -d parranda_events"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Ollama optimizado para modelos pequeños
  ollama:
    image: ollama/ollama:latest
    container_name: parranda_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_QUEUE=2
    networks:
      - parranda_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # n8n para workflows
  n8n:
    image: n8nio/n8n:latest
    container_name: parranda_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=${GITPOD_WORKSPACE_URL:-http://localhost:5678}/
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=parranda2024
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=parranda_events
      - DB_POSTGRESDB_USER=parranda_user
      - DB_POSTGRESDB_PASSWORD=parranda_pass123
      # Variables para Telegram (agregar después)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - SUPERVISOR_CHAT_ID=${SUPERVISOR_CHAT_ID:-}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parranda_network

  # Open WebUI optimizado
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: parranda_chat
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=parranda_secret_2024
      - DEFAULT_MODELS=phi3:mini
      - WEBUI_AUTH=False
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - parranda_network

  # Redis para cache (opcional pero mejora rendimiento)
  redis:
    image: redis:7-alpine
    container_name: parranda_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    networks:
      - parranda_network

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local
  n8n_data:
    driver: local
  open_webui_data:
    driver: local
  redis_data:
    driver: local

networks:
  parranda_network:
    driver: bridgeversion: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: parranda_db
    environment:
      POSTGRES_DB: parranda_events
      POSTGRES_USER: parranda_user
      POSTGRES_PASSWORD: parranda_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parranda_network

  ollama:
    image: ollama/ollama:latest
    container_name: parranda_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - parranda_network

  n8n:
    image: n8nio/n8n:latest
    container_name: parranda_n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://5678-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=parranda2024
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - parranda_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: parranda_chat
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=parranda_secret_2024
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - parranda_network

volumes:
  postgres_data:
  ollama_data:
  n8n_data:
  open_webui_data:

networks:
  parranda_network:
    driver: bridge
