version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: parranda_db
    environment:
      POSTGRES_DB: parranda_events
      POSTGRES_USER: parranda_user
      POSTGRES_PASSWORD: parranda_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parranda_network

  ollama:
    image: ollama/ollama:latest
    container_name: parranda_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - parranda_network

  n8n:
    image: n8nio/n8n:latest
    container_name: parranda_n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://5678-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=parranda2024
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - parranda_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: parranda_chat
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=parranda_secret_2024
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - parranda_network

volumes:
  postgres_data:
  ollama_data:
  n8n_data:
  open_webui_data:

networks:
  parranda_network:
    driver: bridge
