services:
  postgres:
    image: postgres:15-alpine
    container_name: parranda_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: parranda_events
      POSTGRES_USER: parranda_user
      POSTGRES_PASSWORD: parranda_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parranda_network

  n8n:
    image: n8nio/n8n:latest
    container_name: parranda_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=parranda2024
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - parranda_network

  parranda-chat:
    build: 
      context: ./chat-app
      dockerfile: Dockerfile
    container_name: parranda_chat_openai
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://parranda_user:parranda_pass123@postgres:5432/parranda_events
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/escalacion-supervisor
      - PORT=3000
    depends_on:
      - postgres
      - n8n
    networks:
      - parranda_network

volumes:
  postgres_data:
  n8n_data:

networks:
  parranda_network:
    driver: bridge